#!/bin/sh

config="${XDG_CONFIG_HOME:-$HOME/.config}/abook/abookrc"
data="${XDG_DATA_HOME:-$HOME/.local/share}/abook/addressbook"

command -v abook >/dev/null 2>&1 || exit 1
[ -s "$data" ] || exit 0

exec abook -C "$config" --datafile "$data" --mutt-query "$@"
