#!/usr/bin/env bash

set -e

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"
DOTBOT_BIN="bin/dotbot"

cd "$(dirname "${BASH_SOURCE[0]}")"
INSTALL_DIR="$(pwd)"
BASEDIR="$(git rev-parse --show-toplevel)"

git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

"${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"

! command -v zsh >/dev/null 2>&1 || exec zsh
