#!/bin/bash

[ $# -eq 1 ] || { echo "Specify what to do" >&2; exit 1; }

case "$1" in
	"--init") INIT=1;;
	"--update") INIT=0;;
	*) echo "Unknown option"; exit 1;;
esac

if (( $INIT )); then
	git submodule update --init --recursive --jobs 8 --depth 1 2>&1 \
		| grep "Cloning into" \
		|| ! (( ${PIPESTATUS[0]} ))
else
	git submodule update --remote
fi
